/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AuthForm: typeof import('./components/authorization/AuthForm.vue')['default']
    DateFilter: typeof import('./components/reports/Filters/DateFilter.vue')['default']
    Disput: typeof import('./components/reports/Disput.vue')['default']
    Filter: typeof import('./components/reports/components/Filter.vue')['default']
    Filters: typeof import('./components/reports/Filters/Filters.vue')['default']
    Graph: typeof import('./components/reports/components/Graph.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/LineChart/LineChart.vue')['default']
    Profit: typeof import('./components/reports/Profit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesReturns: typeof import('./components/reports/SalesReturns.vue')['default']
    SellersReturn: typeof import('./components/reports/SellersReturn.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Table: typeof import('./components/reports/components/Table.vue')['default']
    TypeFilter: typeof import('./components/reports/Filters/TypeFilter.vue')['default']
    UIButton: typeof import('./components/authorization/UIButton.vue')['default']
    UICheckbox: typeof import('./components/authorization/UICheckbox.vue')['default']
    UIInput: typeof import('./components/authorization/UIInput.vue')['default']
  }
}
